### ISSUE TITLE
verify for code injection.

### ISSUE THREAD

**Issue by simshadows** [coding-buddies-discord/cb-bots#22]
For example, I demonstrated this by setting my alt account's username to `lmao **ayy** lmao`. This leads to:

![ayy](https://user-images.githubusercontent.com/13399999/157343527-7f0af1af-0772-48e4-947a-d14a44bf6f90.png)

Fortunately, the Discord UI prevents us from setting usernames that include `@` or `#` symbols, which is a layer of prevention for a lot of user and channel mentions (including the `@everyone` mention). However, I still think `@` and `#` should also be looked into for escaping. I suggest either checking if `@` and `#` are restricted server-side, or maybe implementing the escapes anyway if it's easy and cheap to do so.

**Comment by Claudi0-V** [comment]
as far as I can see, escaping all discord markdown characters is the only solution there.

**Comment by simshadows** [comment]
and piss easy to implement

**Comment by Claudi0-V** [comment]
Although this issue is solved since #36 we should be careful about code injection. in fact #36 needed an extra fix (#40 ) to deal with html injection. 

due to this i'm pinning this issue
