### ISSUE TITLE
bot breaks when --m flag is passed when giving a point

### ISSUE THREAD

**Issue by Claudi0-V** [coding-buddies-discord/cb-bots#85]
the bot is breaking when someone is giving a point with the `--m` flag. since we now have a option to see global points and each table will show your total points (channel or global), I'm in favor of removing the `--m` flag and everything that comes with

**Comment by Claudi0-V** [comment]
here's the error:
![image](https://user-images.githubusercontent.com/30845840/209195116-42c4398a-fdf0-4191-94d0-47f0637c1749.png)

it occurs because `countGivenPoint`, which is now in `BuddiesModel`, doesnt have a reference to `user`. this method is only called when `--m` is passed.

**Comment by waream2** [comment]
I agree, I think it was a really good way to maintain the original way the bot would respond to points but your emoji reaction response is much better. 

Let's kill it.

**Comment by Claudi0-V** [comment]
solved with #90
